---
- name:  Jenkins | Add repository jenkins TLS
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Jenkins | Import key for repository
  ansible.builtin.rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

- name: Jenkins | Install dependencies
  ansible.builtin.dnf:
    name:
      - jenkins
      - java-11-openjdk

- name: Jenkins | Started jenkins service
  ansible.builtin.service:
    name: jenkins
    state: started

- name: Jenkins | Wait started Jenkins
  ansible.builtin.wait_for:
    path: /var/lib/jenkins/secrets/initialAdminPassword

- name: Jenkins | Get file password instalations
  ansible.builtin.slurp:
    src: /var/lib/jenkins/secrets/initialAdminPassword
  register: installpass

- name: Jenkins | Print password instalations
  ansible.builtin.debug:
    msg: "{{ installpass['content'] | b64decode }}"
